# Generated by Django 4.0.3 on 2022-04-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название дисциплины')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание дисциплины')),
                ('total', models.CharField(max_length=200, verbose_name='Максимальное количество баллов')),
                ('average', models.CharField(max_length=200, verbose_name='Средний балл группы')),
            ],
            options={
                'verbose_name': 'Дисциплину',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
    ]
